/**
 * The image record.
 *
 * "If an image has no row in this sheet, it does not go on the website."
 * That rule is enforced here rather than in a spreadsheet: SiteImage takes a
 * key into this registry, so an image with no record cannot be rendered, and
 * `npm run verify:data` fails the build if a file appears in public/images
 * without an entry.
 *
 * The array is empty because no photography has been taken yet. That is the
 * honest state, and it is why the site currently carries no images.
 *
 * TODO(images): add a record per delivered photograph. Never add one without
 * a licence you can produce - a stock agency sending an invoice in two years
 * is an avoidable and expensive mistake for a new company.
 * See docs/images.md and pm-travel-photo-layout.html.
 */

export type ImageSource =
  | "pm_original"
  | "commissioned"
  | "unsplash"
  | "pexels"
  | "wikimedia"
  | "adobe_stock"
  | "getty"
  | "shutterstock"
  | "stocksy"
  | "onmt";

/**
 * Sources that may depict PM Travel's own operation, staff, vehicles or
 * premises. Anything else is scenery only.
 *
 * Stock photography of people must never be presented as our staff or our
 * clients, and no generated image of any kind is permitted.
 */
export const OPERATIONAL_SOURCES: ImageSource[] = ["pm_original", "commissioned"];

export type ImageRecord = {
  /** Key used in code. Also the filename stem under public/images/. */
  key: string;
  /** Path under public/, e.g. "/images/office-gueliz.jpg". */
  src: string;
  /** Intrinsic size. Required, so the page cannot shift while loading. */
  width: number;
  height: number;
  /**
   * What is actually in the image, for someone who cannot see it.
   * Accessibility first - keyword stuffing here is both useless and wrong.
   */
  alt: string;
  source: ImageSource;
  /** Photographer or contributor. */
  creator: string;
  /** The exact licence, e.g. "Unsplash Licence", "Adobe Standard". */
  licence: string;
  /** Link or file reference to the certificate, invoice or written permission. */
  licenceProof: string;
  /** ISO date. */
  acquiredOn: string;
  commercialUse: true;
  restrictions?: string;
  location?: string;
  /**
   * Whether a signed model release exists for every recognisable person.
   * No release, no publication.
   */
  modelRelease?: boolean;
  /** True for the single hero image only. Everything else loads lazily. */
  priority?: boolean;
};

export const IMAGES: ImageRecord[] = [
  {
    key: "b1-marrakech-hero",
    src: "/images/b1-marrakech-hero.jpg",
    width: 2400,
    height: 1596,
    alt: "The Koutoubia minaret rising above the rooftops of Marrakech, with the snow-covered peaks of the High Atlas behind the city.",
    source: "unsplash",
    creator: "Paul Macallan (@pemacallan)",
    licence: "Unsplash Licence",
    licenceProof:
      "https://unsplash.com/photos/koutoubia-mosque-minaret-in-marrakesh-CFKksjYRSQ8",
    acquiredOn: "2026-09-12",
    commercialUse: true,
    restrictions:
      "Free commercial use, no attribution required under the Unsplash Licence. Credit given anyway on /about. Destination scenery only - never usable for anything depicting PM Travel's own operation.",
    location: "Marrakech, Morocco",
  },
  {
    key: "b2-marrakech-medersa",
    src: "/images/b2-marrakech-medersa.jpg",
    width: 1100,
    height: 1650,
    alt: "The courtyard of the Ben Youssef Medersa in Marrakech, seen through a carved archway, with zellige tilework and a still central pool.",
    source: "unsplash",
    creator: "Alex Azabache",
    licence: "Unsplash Licence",
    licenceProof:
      "https://unsplash.com/photos/medersa-ben-youssef-during-daytime-YSabBvW1aR4",
    acquiredOn: "2026-09-12",
    commercialUse: true,
    restrictions:
      "Destination scenery only. Never usable for anything depicting PM Travel's own operation.",
    location: "Marrakech, Morocco",
  },
  {
    key: "b4-atlas-imlil",
    src: "/images/b4-atlas-imlil.jpg",
    width: 1600,
    height: 1067,
    alt: "A High Atlas village of earth-built houses on a mountainside above a wooded valley, with the access road visible cut into the slope.",
    source: "unsplash",
    creator: "Louis Hansel",
    licence: "Unsplash Licence",
    licenceProof:
      "https://unsplash.com/photos/photo-of-brown-houses-surrounded-by-green-trees-erg9zCloOgs",
    acquiredOn: "2026-09-12",
    commercialUse: true,
    restrictions:
      "Destination scenery only. Never usable for anything depicting PM Travel's own operation.",
    location: "High Atlas, Morocco",
  },
  {
    key: "b6-merzouga",
    src: "/images/b6-merzouga.jpg",
    width: 1600,
    height: 1200,
    alt: "Wind-rippled orange sand of the Erg Chebbi dunes near Merzouga, rising to a clean horizon under a clear sky.",
    source: "unsplash",
    creator: "Mark Kuiper",
    licence: "Unsplash Licence",
    licenceProof:
      "https://unsplash.com/photos/brown-sand-under-blue-and-white-sky-_UJTBae6whA",
    acquiredOn: "2026-09-12",
    commercialUse: true,
    restrictions:
      "Destination scenery only. Never usable for anything depicting PM Travel's own operation.",
    location: "Erg Chebbi, Merzouga, Morocco",
  },
  {
    key: "b9-erg-chebbi-camels",
    src: "/images/b9-erg-chebbi-camels.jpg",
    width: 2400,
    height: 1800,
    alt: "A line of camels walking along the crest of the orange Erg Chebbi dunes near Merzouga in early morning light, under a deep blue sky.",
    source: "unsplash",
    creator: "Carlos Leret (@leret)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/camels-in-a-desert-kiYzznir-uo",
    acquiredOn: "2026-09-12",
    commercialUse: true,
    restrictions:
      "Destination scenery only, no people in frame. Resized from the 4060x3045 original. Never usable for anything depicting PM Travel's own operation.",
    location: "Erg Chebbi, Merzouga, Morocco",
  },
  {
    key: "b3-agafay",
    src: "/images/b3-agafay.jpg",
    width: 1100,
    height: 1467,
    alt: "A dirt track winding between the bare, rounded brown hills of the Agafay desert, with the blue ridges of the Atlas Mountains on the horizon.",
    source: "unsplash",
    creator: "Chloé Lefleur (@chloe_lefleur)",
    licence: "Unsplash Licence",
    licenceProof:
      "https://unsplash.com/photos/a-view-of-a-desert-landscape-with-mountains-in-the-distance-jMb3w4jsorA",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions:
      "Destination scenery only, no people in frame. Resized from the original. Never usable for anything depicting PM Travel's own operation.",
    location: "Agafay, Morocco",
  },
  {
    key: "b3b-agafay-camp",
    src: "/images/b3b-agafay-camp.jpg",
    width: 1920,
    height: 1280,
    alt: "A shade canopy and low seating on stony ground at the edge of the Agafay desert, looking out over rolling brown hills towards distant mountains in haze.",
    source: "unsplash",
    creator: "Kostas Fotiadis (@kosfoti)",
    licence: "Unsplash Licence",
    licenceProof:
      "https://unsplash.com/photos/a-tent-set-up-in-the-middle-of-a-desert-cqR7hPZmA8w",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions:
      "Destination scenery only. One distant figure, not identifiable. Not a PM Travel site or camp, and never usable as one.",
    location: "Agafay, Morocco",
  },
  {
    key: "b5-essaouira-port",
    src: "/images/b5-essaouira-port.jpg",
    width: 1920,
    height: 1275,
    alt: "The fishing port of Essaouira, with rows of blue wooden boats moored inside the harbour wall, a boat under construction on the quay and the Atlantic beyond.",
    source: "unsplash",
    creator: "Ma He (@maihe)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/xiBE9G0godc",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions:
      "Destination scenery only. Distant passers-by on the quay, none identifiable. Never usable for anything depicting PM Travel's own operation.",
    location: "Essaouira, Morocco",
  },
  {
    key: "b7-fes-medina",
    src: "/images/b7-fes-medina.jpg",
    width: 1920,
    height: 1281,
    alt: "The densely packed flat rooftops of the Fes medina seen from above, a sea of sand-coloured and white buildings stretching to the hills.",
    source: "unsplash",
    creator: "Kyle Frost (@kylefrost)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/uuFcJnLi540",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions:
      "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Fes, Morocco",
  },
  {
    key: "b7b-fes-alley",
    src: "/images/b7b-fes-alley.jpg",
    width: 1100,
    height: 1467,
    alt: "Looking up a narrow alley in the Fes medina, past a carved stucco doorway and cedar eaves towards a strip of pale sky.",
    source: "unsplash",
    creator: "moroccan zest (@moroccanzest)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/JLNhr2TTsJA",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions:
      "Destination scenery only, no people in frame. Resized from the original. Never usable for anything depicting PM Travel's own operation.",
    location: "Fes, Morocco",
  },
  {
    key: "c1-casablanca-sea",
    src: "/images/c1-casablanca-sea.jpg",
    width: 1920,
    height: 1280,
    alt: "The Hassan II Mosque and its tall minaret seen across the Atlantic from the Casablanca shoreline, with apartment blocks along the coast.",
    source: "unsplash",
    creator: "Maria Krasnova (@salty_morning)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/_Faweyea_10",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Casablanca, Morocco",
  },
  {
    key: "c1b-casablanca-mosque",
    src: "/images/c1b-casablanca-mosque.jpg",
    width: 1920,
    height: 1275,
    alt: "The minaret of the Hassan II Mosque in Casablanca rising above the arcaded esplanade and green-tiled roofs, under a clear sky.",
    source: "unsplash",
    creator: "Hans-Jürgen Weinhardt (@hansjuergen)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/xijil3cOsis",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only. Distant visitors on the esplanade, none identifiable. Never usable for anything depicting PM Travel's own operation.",
    location: "Casablanca, Morocco",
  },
  {
    key: "c2-rabat-hassan-tower",
    src: "/images/c2-rabat-hassan-tower.jpg",
    width: 1920,
    height: 1440,
    alt: "The unfinished Hassan Tower in Rabat at dusk, with rows of stone column bases standing on the esplanade in front of it.",
    source: "unsplash",
    creator: "Hongbin (@hbsun2013)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/QOse_cZFWzo",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only. Distant visitors, none identifiable. Never usable for anything depicting PM Travel's own operation.",
    location: "Rabat, Morocco",
  },
  {
    key: "c2b-rabat-tower-detail",
    src: "/images/c2b-rabat-tower-detail.jpg",
    width: 1100,
    height: 1650,
    alt: "Close view of the carved sandstone face of the Hassan Tower in Rabat, with its interlaced arch patterns.",
    source: "unsplash",
    creator: "mehdi lamaaffar (@mehdi_lamaaffar)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/eoY93dm3UvQ",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Rabat, Morocco",
  },
  {
    key: "c3-tangier-night",
    src: "/images/c3-tangier-night.jpg",
    width: 1920,
    height: 1280,
    alt: "Tangier at dusk from above, the lit medina and seafront road curving along the bay towards the port.",
    source: "unsplash",
    creator: "Raúl Cacho Oses (@raulcachophoto)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/atwIEcpyeSM",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Tangier, Morocco",
  },
  {
    key: "c3b-tangier-cave",
    src: "/images/c3b-tangier-cave.jpg",
    width: 1100,
    height: 1397,
    alt: "The Atlantic seen through the rock opening of a sea cave near Tangier, waves breaking below.",
    source: "unsplash",
    creator: "Michael Starkie (@starkie_pics)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/UnzkvCEk1Mg",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Tangier, Morocco",
  },
  {
    key: "c4-chefchaouen",
    src: "/images/c4-chefchaouen.jpg",
    width: 1920,
    height: 1280,
    alt: "The blue and white houses of Chefchaouen stacked up the hillside below a wooded ridge.",
    source: "unsplash",
    creator: "Pretty Pink (@infinitexplorer)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/NncAbldgViA",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Chefchaouen, Morocco",
  },
  {
    key: "c4b-chefchaouen-steps",
    src: "/images/c4b-chefchaouen-steps.jpg",
    width: 1100,
    height: 1650,
    alt: "A stepped blue alley in the Chefchaouen medina, with tiled walls, a painted door and wrought-iron railings.",
    source: "unsplash",
    creator: "Mauro Lima (@limamauro23)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/1SiIhR2uGvo",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Private doors: never cropped to single out a residence. Never usable for anything depicting PM Travel's own operation.",
    location: "Chefchaouen, Morocco",
  },
  {
    key: "c5-agadir-taghazout",
    src: "/images/c5-agadir-taghazout.jpg",
    width: 1920,
    height: 1440,
    alt: "Whitewashed houses and blue fishing boats above the beach at Taghazout, the surf village north of Agadir.",
    source: "unsplash",
    creator: "Louis Hansel (@louishansel)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/aqJfoLKFz6c",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Taken at Taghazout, not Agadir city; the alt text says so. Destination scenery only. Never usable for anything depicting PM Travel's own operation.",
    location: "Taghazout, near Agadir, Morocco",
  },
  {
    key: "c5b-agadir-surf",
    src: "/images/c5b-agadir-surf.jpg",
    width: 1100,
    height: 1375,
    alt: "Atlantic waves rolling onto a wide beach near Agadir, with rocky headlands in the sea mist behind.",
    source: "unsplash",
    creator: "Juli Kosolapova (@yuli_superson)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/CEeXw7a_5LA",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Agadir, Morocco",
  },
  {
    key: "c6-ouarzazate-kasbah",
    src: "/images/c6-ouarzazate-kasbah.jpg",
    width: 1920,
    height: 1280,
    alt: "The earthen towers of a kasbah near Ouarzazate against a deep blue sky, with a palm tree in the foreground.",
    source: "unsplash",
    creator: "Desert Morocco Adventure (@dmadventure)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/DbdUWca18g0",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Published by a tour company; never usable to imply that company's services are ours.",
    location: "Ouarzazate, Morocco",
  },
  {
    key: "c6b-ouarzazate-village",
    src: "/images/c6b-ouarzazate-village.jpg",
    width: 1920,
    height: 1282,
    alt: "An earthen village among green fields and trees below red and grey mountains in the Ouarzazate region.",
    source: "unsplash",
    creator: "Abdou Faiz (@abdoufaiz)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/KMcqhDEb03c",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Ouarzazate region, Morocco",
  },
  {
    key: "c7-ait-ben-haddou",
    src: "/images/c7-ait-ben-haddou.jpg",
    width: 1920,
    height: 1080,
    alt: "The ksar of Aït Ben Haddou climbing its hillside, earthen houses and towers below the granary at the summit.",
    source: "unsplash",
    creator: "Abdou Faiz (@abdoufaiz)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/lA-P8-vagrI",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Aït Ben Haddou, Morocco",
  },
  {
    key: "c7b-ait-ben-haddou-ksar",
    src: "/images/c7b-ait-ben-haddou-ksar.jpg",
    width: 1100,
    height: 1650,
    alt: "The earthen village of Aït Ben Haddou spread along the hillside above palm trees and desert scrub.",
    source: "unsplash",
    creator: "Marcel L. (@ml_75)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/hTtHe8UAJRg",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Aït Ben Haddou, Morocco",
  },
  {
    key: "c8-dades-gorge",
    src: "/images/c8-dades-gorge.jpg",
    width: 1920,
    height: 1336,
    alt: "The road into the Dades Gorges climbing in tight hairpin bends between steep, eroded rock walls.",
    source: "unsplash",
    creator: "Abdou Faiz (@abdoufaiz)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/AWPNSJVIwkg",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation or vehicles.",
    location: "Dades Gorges, Morocco",
  },
  {
    key: "c8b-dades-hairpins",
    src: "/images/c8b-dades-hairpins.jpg",
    width: 1100,
    height: 1100,
    alt: "The hairpin road of the Dades Gorges near Boumalne Dades, winding up a narrow canyon in low evening light.",
    source: "unsplash",
    creator: "Mohamed Abira (@moroccopictures)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/bq_u2CZXFb8",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Boumalne Dades, Morocco",
  },
  {
    key: "c9-zagora-dunes",
    src: "/images/c9-zagora-dunes.jpg",
    width: 1920,
    height: 1280,
    alt: "Smooth orange sand dunes near Zagora rising to a crest under a clear blue sky.",
    source: "unsplash",
    creator: "Marius Zetzmann (@simplepic)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/yb38Gt1mQ1c",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Zagora, Morocco",
  },
  {
    key: "c9b-zagora-cliffs",
    src: "/images/c9b-zagora-cliffs.jpg",
    width: 1100,
    height: 1650,
    alt: "A flat-topped rocky ridge near Zagora catching the sun against a wide, clear blue sky.",
    source: "unsplash",
    creator: "Raúl Mermans García (@raulmermans)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/oWzVpeYyJ-w",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Zagora, Morocco",
  },
  {
    key: "c10-dakhla-lagoon",
    src: "/images/c10-dakhla-lagoon.jpg",
    width: 1920,
    height: 1078,
    alt: "Aerial view of the shallow green water and sand of the Dakhla lagoon, with a kite and a small white boat on the shore.",
    source: "unsplash",
    creator: "Dekeister Leopold (@eyesgroup)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/Cn-EpLcknlY",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Branding on the kite is incidental. Never usable for anything depicting PM Travel's own operation.",
    location: "Dakhla lagoon, Morocco",
  },
  {
    key: "c10b-dakhla-beach",
    src: "/images/c10b-dakhla-beach.jpg",
    width: 1100,
    height: 1650,
    alt: "An off-road vehicle crossing the sandy shore at Dakhla, with low dunes and the calm sea behind it.",
    source: "unsplash",
    creator: "Khalid El Hadrami (@khalid02)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/31ZGtXBhIG4",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, driver not visible. Not a PM Travel vehicle and never usable as one.",
    location: "Dakhla, Morocco",
  },
  {
    key: "c11-ourika-valley",
    src: "/images/c11-ourika-valley.jpg",
    width: 1100,
    height: 1375,
    alt: "Terraced slopes of the Ourika valley in autumn colours, a small house on the hillside and bare High Atlas ridges rising behind.",
    source: "unsplash",
    creator: "Abdelhamid Azoui (@abdelhamid_az)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/BGU0uaY0tJs",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Ourika valley, Morocco",
  },
  {
    key: "c11b-ourika-road",
    src: "/images/c11b-ourika-road.jpg",
    width: 1920,
    height: 1280,
    alt: "A mountain road curving through cedar forest in the Ourika area, below High Atlas peaks with snow on their upper slopes.",
    source: "unsplash",
    creator: "HASSAN AHROUCH (@ssanrouch53art)",
    licence: "Unsplash Licence",
    licenceProof: "https://unsplash.com/photos/CfmIZwBvxNY",
    acquiredOn: "2026-09-13",
    commercialUse: true,
    restrictions: "Destination scenery only, no people in frame. Never usable for anything depicting PM Travel's own operation.",
    location: "Ourika, Morocco",
  },
  // Service photographs for /mice and /morocco-dmc, from Wikimedia Commons.
  // CC BY and CC BY-SA require attribution: the creator and licence are shown
  // in the credits on /about. Resized only, never otherwise altered.
  {
    key: "d1-mice-conference-hall",
    src: "/images/d1-mice-conference-hall.jpg",
    width: 1600,
    height: 1200,
    alt: "A large, empty conference auditorium with rows of red seats rising towards a wide stage under a ceiling of spotlights.",
    source: "wikimedia",
    creator: "Zaizone",
    licence: "CC BY-SA 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Salle_de_conf%C3%A9rence_de_la_Fondation_F%C3%A9lix_Houphou%C3%ABt_Boigny.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Illustrates a conference format only: not a Morocco venue, not one PM Travel has inspected, and never presented as either.",
    location: "Conference hall, Fondation Félix Houphouët-Boigny, Côte d'Ivoire",
  },
  {
    key: "d2-mice-riad-rooftop-pool",
    src: "/images/d2-mice-riad-rooftop-pool.jpg",
    width: 1600,
    height: 1068,
    alt: "A green-tiled plunge pool on a Marrakech riad roof terrace, with sun loungers, potted palms and a canopied daybed under a blue sky.",
    source: "wikimedia",
    creator: "Dutch Morocco Investments SARL",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:11_Terrace_pool_11.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. No people in frame. Not a property PM Travel has contracted or inspected.",
    location: "Riad roof terrace, Marrakech, Morocco",
  },
  {
    key: "d3-mice-bahia-palace",
    src: "/images/d3-mice-bahia-palace.jpg",
    width: 1600,
    height: 2403,
    alt: "A courtyard garden of the Bahia Palace in Marrakech, with orange trees, a carved stone fountain and zellige-tiled paths before arched doorways.",
    source: "wikimedia",
    creator: "Matt Kieffer",
    licence: "CC BY-SA 2.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Palais_de_la_Bahia,_Marrakech_(23984982364).jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Destination scenery only; the palace is a monument, not an event venue offered by PM Travel.",
    location: "Bahia Palace, Marrakech, Morocco",
  },
  {
    key: "d4-mice-menara-terminal-roof",
    src: "/images/d4-mice-menara-terminal-roof.jpg",
    width: 1600,
    height: 1200,
    alt: "The white geometric lattice canopy over the entrance of the Marrakech Menara Airport terminal, with travellers small below it.",
    source: "wikimedia",
    creator: "Jason7825",
    licence: "Public domain",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Marrakech_Menara_Airport_3.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Released into the public domain by the author. People are distant and not identifiable. Never presented as a PM Travel arrival.",
    location: "Marrakech Menara Airport, Morocco",
  },
  {
    key: "d5-dmc-menara-airport",
    src: "/images/d5-dmc-menara-airport.jpg",
    width: 1600,
    height: 1200,
    alt: "The angular white terminal building of Marrakech Menara Airport under a blue sky, with palm trees and cactus planting along the forecourt.",
    source: "wikimedia",
    creator: "瑞丽江的河水",
    licence: "CC BY-SA 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Marrakech_Airport_terminal_1_-_2026-01-31.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Building exterior only. Never presented as a PM Travel vehicle, staff member or arrival.",
    location: "Marrakech Menara Airport, Morocco",
  },
  {
    key: "d6-dmc-riad-patio",
    src: "/images/d6-dmc-riad-patio.jpg",
    width: 1600,
    height: 1217,
    alt: "The planted inner patio of a Marrakech riad, with tall palms around a small pool, a round table and two chairs on a black and white tiled floor.",
    source: "wikimedia",
    creator: "Arnaud 25",
    licence: "CC BY-SA 3.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Riad_Maroc_031.JPG",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Riad Monceau, Marrakech; not a property PM Travel has contracted or inspected.",
    location: "Riad patio, Marrakech, Morocco",
  },
  {
    key: "d7-dmc-covered-souk",
    src: "/images/d7-dmc-covered-souk.jpg",
    width: 1600,
    height: 1064,
    alt: "Souk Semmarine in the Marrakech medina, a covered market street striped with sunlight through a slatted roof, lined with textile and craft stalls.",
    source: "wikimedia",
    creator: "DimiTalen",
    licence: "CC0 1.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Covered_Souk_Semmarine,_Marrakech,_2008.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Public domain dedication. Passers-by are not the subject. No person shown is a PM Travel guide or client, and none may be presented as one.",
    location: "Souk Semmarine, Marrakech, Morocco",
  },
  {
    key: "d8-dmc-jemaa-el-fnaa-sunset",
    src: "/images/d8-dmc-jemaa-el-fnaa-sunset.jpg",
    width: 1600,
    height: 1200,
    alt: "Jemaa el-Fnaa square in Marrakech at sunset, crowded with food stalls under green awnings, with the Koutoubia minaret against a pink sky.",
    source: "wikimedia",
    creator: "Herokk",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Jemaa_el-Fnaa_Marrakech_at_sunset.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Crowd seen from a distance, no identifiable subject. Destination scenery only.",
    location: "Jemaa el-Fnaa, Marrakech, Morocco",
  },
  // Excursion photographs, from Wikimedia Commons. Riders and hikers are
  // helmeted or seen from behind; none is a PM Travel guide or client, and no
  // vehicle or bike shown belongs to PM Travel or a contracted supplier.
  {
    key: "e01-merzouga-quads",
    src: "/images/e01-merzouga-quads.jpg",
    width: 1600,
    height: 1200,
    alt: "Two helmeted riders on quad bikes crossing the orange sand of the Merzouga dunes under a pale sky.",
    source: "wikimedia",
    creator: "SaharaADV",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Merzouga_dune_quad_tour.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Taken in Merzouga, not Agafay; illustrates the activity only. Riders helmeted and not identifiable; not PM Travel clients or equipment.",
    location: "Erg Chebbi dunes, Merzouga, Morocco",
  },
  {
    key: "e03-atlas-pass-cyclist",
    src: "/images/e03-atlas-pass-cyclist.jpg",
    width: 1600,
    height: 1071,
    alt: "A cyclist on a loaded touring bike riding a gravel road over the Col du Tirherhouzine, with bare Atlas ridges under a deep blue sky.",
    source: "wikimedia",
    creator: "Michaela Göd",
    licence: "CC BY-SA 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Mit_dem_Fahrrad_am_Col_du_Tirherhouzine_Marokko.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. A touring bicycle, not an e-bike, in the central High Atlas. Rider seen from the side at a distance; not a PM Travel client or guide.",
    location: "Col du Tirherhouzine, High Atlas, Morocco",
  },
  {
    key: "e04-atlas-road-cyclists",
    src: "/images/e04-atlas-road-cyclists.jpg",
    width: 1600,
    height: 1200,
    alt: "A small group of cyclists far along a winding mountain road between bare, layered hills in the Atlas, under a clear blue sky.",
    source: "wikimedia",
    creator: "Teo Romera",
    licence: "CC BY-SA 2.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Lunar_Bikers-teosaurio.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Taken between Imilchil and Tamtatouchte, not Ourika. Riders are distant and not identifiable.",
    location: "Road from Imilchil to Tamtatouchte, Morocco",
  },
  {
    key: "e05-agafay-camel-caravan",
    src: "/images/e05-agafay-camel-caravan.jpg",
    width: 1600,
    height: 1067,
    alt: "A line of riders on camels following a curving dirt track across the brown stony hills near Agafay.",
    source: "wikimedia",
    creator: "Anual",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Marraquech_028.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Riders seen from a distance and not identifiable; not PM Travel clients.",
    location: "Near Agafay, Marrakech region, Morocco",
  },
  {
    key: "e06-agafay-tracks",
    src: "/images/e06-agafay-tracks.jpg",
    width: 1600,
    height: 1063,
    alt: "Dirt tracks winding across the pale, rolling hills of the Agafay desert towards a flat horizon in soft evening light.",
    source: "wikimedia",
    creator: "Jakub Hałun",
    licence: "CC BY 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Agafay_Desert,_Morocco,_20250125_1848_7298.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution required. No people in frame. Destination scenery only.",
    location: "Agafay desert, Morocco",
  },
  {
    key: "e07-agafay-tent",
    src: "/images/e07-agafay-tent.jpg",
    width: 1600,
    height: 1068,
    alt: "A single nomad-style tent standing alone on the flat stony ground of the Agafay desert, with hazy Atlas ridges on the horizon.",
    source: "wikimedia",
    creator: "Jakub Hałun",
    licence: "CC BY 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Agafay_Desert,_Morocco,_20250125_1819_7292.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution required. No people in frame. Not a camp PM Travel has contracted or inspected.",
    location: "Agafay desert, Morocco",
  },
  {
    key: "e08-setti-fatma-cascade",
    src: "/images/e08-setti-fatma-cascade.jpg",
    width: 1600,
    height: 1200,
    alt: "White water rushing between large grey boulders on the stream below the Setti Fatma waterfalls in the Ourika valley.",
    source: "wikimedia",
    creator: "Abbas9",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Ourika_-_Setti_Fatma_-_Maroc_21.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Setti Fatma, Ourika valley, Morocco",
  },
  {
    key: "e09-imlil-from-aroumd",
    src: "/images/e09-imlil-from-aroumd.jpg",
    width: 1600,
    height: 1063,
    alt: "The green valley floor of Imlil seen from the path above Aroumd, earthen villages among walnut trees between steep brown mountainsides.",
    source: "wikimedia",
    creator: "DimiTalen",
    licence: "CC0 1.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Overview_of_Imlil_from_Aroumd,_Morocco,_2008.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Public domain dedication. No people in frame. Destination scenery only.",
    location: "Imlil valley, High Atlas, Morocco",
  },
  {
    key: "e10-imlil-village",
    src: "/images/e10-imlil-village.jpg",
    width: 1600,
    height: 1200,
    alt: "An Amazigh village of stacked earth and stone houses on a High Atlas slope above terraced fields and autumn trees near Imlil.",
    source: "wikimedia",
    creator: "Mounir Neddi",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Imlil_village,_High_Atlas_Mountains.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No identifiable people. Destination scenery only.",
    location: "Imlil, High Atlas, Morocco",
  },
  {
    key: "e11-toubkal-hikers",
    src: "/images/e11-toubkal-hikers.jpg",
    width: 1600,
    height: 1200,
    alt: "A small group of hikers with backpacks, seen from behind, climbing a stony ridge towards the snow-streaked summit of Jebel Toubkal.",
    source: "wikimedia",
    creator: "Kurinurm",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Jebel_Toubkal_and_a_group_of_hikers.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Hikers seen from behind and not identifiable; not a PM Travel group, guide or client.",
    location: "Jebel Toubkal, High Atlas, Morocco",
  },
  {
    key: "e12-souk-lanterns",
    src: "/images/e12-souk-lanterns.jpg",
    width: 1600,
    height: 1170,
    alt: "Pierced brass and copper lanterns hanging close together in a stall in Souk Haddadine, glowing against the dark.",
    source: "wikimedia",
    creator: "Petar Milošević",
    licence: "CC BY-SA 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Oriental_hanging_lanterns._Souk_Haddadine,_Marrakech_Medina_(%D8%B3%D9%88%D9%82_%D8%A7%D9%84%D8%AD%D8%AF%D8%A7%D8%AF%D9%8A%D9%86_%D9%85%D8%B1%D8%A7%D9%83%D8%B4).jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Souk Haddadine, Marrakech medina, Morocco",
  },
  {
    key: "e13-agafay-desert-track",
    src: "/images/e13-agafay-desert-track.jpg",
    width: 1600,
    height: 1063,
    alt: "A rough dirt track running across the stony Agafay desert towards low hills, with the High Atlas faint on the horizon.",
    source: "wikimedia",
    creator: "Jakub Hałun",
    licence: "CC BY 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Agafay_Desert,_Morocco,_20250125_1759_7281.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution required. No people in frame. Destination scenery only.",
    location: "Agafay desert, Morocco",
  },
  {
    key: "e14-majorelle-villa",
    src: "/images/e14-majorelle-villa.jpg",
    width: 1600,
    height: 1062,
    alt: "The cobalt blue and yellow villa of the Majorelle Garden in Marrakech, framed by cacti, palms and a blue-tiled pool.",
    source: "wikimedia",
    creator: "Viault",
    licence: "CC BY-SA 3.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Le_jardin_des_majorelle_21.JPG",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Majorelle Garden, Marrakech, Morocco",
  },
  {
    key: "e15-jardin-secret",
    src: "/images/e15-jardin-secret.jpg",
    width: 1600,
    height: 1067,
    alt: "A quiet corner of Le Jardin Secret in the Marrakech medina, with orange trees and planted beds around a small fountain and a white bench.",
    source: "wikimedia",
    creator: "muffinn from Worcester, UK",
    licence: "CC BY 2.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Marrakech_-_Le_Jardin_Secret_(49110722413).jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution required. No people in frame. Destination scenery only.",
    location: "Le Jardin Secret, Marrakech medina, Morocco",
  },
  {
    key: "e16-ben-youssef-madrasa",
    src: "/images/e16-ben-youssef-madrasa.jpg",
    width: 1600,
    height: 1200,
    alt: "The main courtyard of the Ben Youssef Madrasa, with carved stucco and cedar walls, zellige tiling and a long marble pool before the prayer hall arch.",
    source: "wikimedia",
    creator: "R Prazeres",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Ben_Youssef_Madrasa_DSCF5986.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Ben Youssef Madrasa, Marrakech, Morocco",
  },
  {
    key: "e17-saadian-tombs",
    src: "/images/e17-saadian-tombs.jpg",
    width: 1600,
    height: 1065,
    alt: "The Hall of Twelve Columns in the Saadian Tombs, with marble tombs on a zellige floor beneath carved stucco arches and a gilded ceiling.",
    source: "wikimedia",
    creator: "Matt Kieffer",
    licence: "CC BY-SA 2.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Saadian_Tombs,_Marrakech,_Morocco,_2018.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Saadian Tombs, Marrakech, Morocco",
  },
  {
    key: "e18-jemaa-el-fna-dusk",
    src: "/images/e18-jemaa-el-fna-dusk.jpg",
    width: 1600,
    height: 1071,
    alt: "Jemaa el-Fna square seen from above at dusk, its lit stalls and juice carts glowing under an orange sky with the Koutoubia minaret on the skyline.",
    source: "wikimedia",
    creator: "procsilas",
    licence: "CC BY 2.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Jemaa_el-Fnaa_at_night.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution required. People are distant silhouettes and not identifiable; not a PM Travel group or client.",
    location: "Jemaa el-Fna, Marrakech, Morocco",
  },
  {
    key: "e19-spice-shop-arch",
    src: "/images/e19-spice-shop-arch.jpg",
    width: 1600,
    height: 2133,
    alt: "A spice and herbalist shop in the Marrakech medina seen through a carved white arch, with jars on wooden shelves and baskets of dried roses at the door.",
    source: "wikimedia",
    creator: "Ekaterina Kvelidze",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Moroccan_spices_1.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Marrakech medina, Morocco",
  },
  {
    key: "e20-spice-shop",
    src: "/images/e20-spice-shop.jpg",
    width: 1600,
    height: 1200,
    alt: "Tall cones of ground spices above tubs of cinnamon bark, dried rosebuds and other spices at a shop front in the Marrakech medina.",
    source: "wikimedia",
    creator: "Doug Knuth",
    licence: "CC BY-SA 2.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Spice_Shop_-_Marrakech,_Morocco_-_May_2007.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Marrakech medina, Morocco",
  },
  {
    key: "e21-spice-market-roses",
    src: "/images/e21-spice-market-roses.jpg",
    width: 1600,
    height: 1200,
    alt: "A close-up of dyed pot-pourri and dried flower buds in pink, blue, yellow and green, piled high at a Marrakech spice market stall.",
    source: "wikimedia",
    creator: "Michael Day",
    licence: "CC BY 2.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Spice_Market,_Marakech_(2242330687).jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution required. No people in frame. Destination scenery only.",
    location: "Marrakech medina, Morocco",
  },
  {
    key: "e22-essaouira-citadel",
    src: "/images/e22-essaouira-citadel.jpg",
    width: 1600,
    height: 1067,
    alt: "Rows of blue wooden fishing boats moored below the stone tower and arched sea walls of the Essaouira port citadel.",
    source: "wikimedia",
    creator: "Ahmed.magdy",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Essaouira_Citadel.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Essaouira port, Morocco",
  },
  {
    key: "e23-essaouira-skala",
    src: "/images/e23-essaouira-skala.jpg",
    width: 1600,
    height: 1067,
    alt: "The square stone bastion of the Skala du Port in Essaouira under a grey sky, with gulls wheeling above and a breakwater in front.",
    source: "wikimedia",
    creator: "Adam Harangozó",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Skala_du_Port,_Essaouira_01.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Skala du Port, Essaouira, Morocco",
  },
  {
    key: "e24-palmeraie-camels-resting",
    src: "/images/e24-palmeraie-camels-resting.jpg",
    width: 1600,
    height: 1062,
    alt: "Saddled camels with red and white blankets resting on the sand under tall date palms in the Marrakech Palmeraie.",
    source: "wikimedia",
    creator: "Viault",
    licence: "CC BY-SA 3.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:La_Palmeraie_de_Marrakech_707.JPG",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Not a PM Travel supplier's animals.",
    location: "Palmeraie, Marrakech, Morocco",
  },
  {
    key: "e25-palmeraie-camels-standing",
    src: "/images/e25-palmeraie-camels-standing.jpg",
    width: 1600,
    height: 1062,
    alt: "Two saddled camels standing on open ground among scattered date palms in the Marrakech Palmeraie under a blue sky.",
    source: "wikimedia",
    creator: "Viault",
    licence: "CC BY-SA 3.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:La_Palmeraie_de_Marrakech_701.JPG",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Not a PM Travel supplier's animals.",
    location: "Palmeraie, Marrakech, Morocco",
  },
  {
    key: "e26-menara-pavilion",
    src: "/images/e26-menara-pavilion.jpg",
    width: 1600,
    height: 848,
    alt: "The green-roofed Menara pavilion reflected at the far end of its wide water basin, with palms and olive trees under a blue sky.",
    source: "wikimedia",
    creator: "JopkeB",
    licence: "CC BY-SA 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Menara_Bassin_and_Garden_Pavilion,_Marrakech_1989.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. Photographed in 1989. No people in frame. Destination scenery only.",
    location: "Menara Gardens, Marrakech, Morocco",
  },
  {
    key: "e27-caleche-horse",
    src: "/images/e27-caleche-horse.jpg",
    width: 1600,
    height: 1200,
    alt: "A dark horse in decorated harness waiting with its green calèche at a carriage stand in Marrakech.",
    source: "wikimedia",
    creator: "mwanasimba from La Réunion",
    licence: "CC BY-SA 2.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Caleche_in_Marrakech_(2902170296).jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Any people are in the background and not identifiable. Not a PM Travel supplier's carriage.",
    location: "Marrakech, Morocco",
  },
  {
    key: "e28-lalla-takerkoust-lake",
    src: "/images/e28-lalla-takerkoust-lake.jpg",
    width: 1600,
    height: 1060,
    alt: "Eucalyptus trees on dry, sandy slopes above the blue water of the Lalla Takerkoust lake south of Marrakech.",
    source: "wikimedia",
    creator: "Bertramz",
    licence: "CC BY-SA 3.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:LallaTakerkoust,lake.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Lalla Takerkoust lake, Al Haouz, Morocco",
  },
  {
    key: "e29-desert-camp-night",
    src: "/images/e29-desert-camp-night.jpg",
    width: 1600,
    height: 1200,
    alt: "A small desert camp glowing with lamps at night on a wide stony plain below a dark hill, under a starry sky.",
    source: "wikimedia",
    creator: "Richard Allaway",
    licence: "CC BY 2.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Extreme_Environments_Night_time_at_the_desert_camp,_Zagora,_Morocco_(35421622636).jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution required. Taken near Zagora, not Agafay: illustrates a desert camp at night only, never presented as a camp PM Travel uses.",
    location: "Near Zagora, Morocco",
  },
  {
    key: "e30-milky-way-tree",
    src: "/images/e30-milky-way-tree.jpg",
    width: 1600,
    height: 2404,
    alt: "The Milky Way arching across a deep blue night sky above a lone tree lit on a desert ridge.",
    source: "wikimedia",
    creator: "Amine reboukh",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:The_tree_of_sahara.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions:
      "Attribution and share-alike required. Taken near Merzouga, not Agafay: illustrates the desert night sky only. No people in frame.",
    location: "Near Merzouga, Morocco",
  },
  {
    key: "e31-ourika-village",
    src: "/images/e31-ourika-village.jpg",
    width: 1600,
    height: 1200,
    alt: "Village houses on a wooded slope of the Ourika valley, below a snow-capped High Atlas peak and a deep blue sky.",
    source: "wikimedia",
    creator: "M1abdelrahman",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Ourika_1.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Ourika valley, Morocco",
  },
  {
    key: "e32-ourika-pottery",
    src: "/images/e32-ourika-pottery.jpg",
    width: 1600,
    height: 1060,
    alt: "Hundreds of terracotta pots stacked on a stone terrace along the Ourika valley road, below an earthen kasbah tower.",
    source: "wikimedia",
    creator: "Maxim Massalitin",
    licence: "CC BY-SA 2.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Ourika_sightseeing_(8162699524).jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Not a PM Travel supplier.",
    location: "Ourika valley, Morocco",
  },
  {
    key: "e33-oukaimeden-road",
    src: "/images/e33-oukaimeden-road.jpg",
    width: 1600,
    height: 1062,
    alt: "A mountain road winding around a pine-covered spur towards Oukaïmeden, below snow-covered High Atlas ridges.",
    source: "wikimedia",
    creator: "MED.BENALLA",
    licence: "CC BY-SA 3.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:One_of_the_scenic_locations_of_the_Oukaimeden_village.JPG",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Oukaïmeden, High Atlas, Morocco",
  },
  {
    key: "e34-oukaimeden-plateau",
    src: "/images/e34-oukaimeden-plateau.jpg",
    width: 1600,
    height: 900,
    alt: "Cedar and pine trees on the high Oukaïmeden plateau, with a long red mountain ridge behind under a clear blue sky.",
    source: "wikimedia",
    creator: "Zahra IMEHLI",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Oukaimeden_1.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Oukaïmeden, High Atlas, Morocco",
  },
  {
    key: "e35-aroumd-village",
    src: "/images/e35-aroumd-village.jpg",
    width: 1600,
    height: 1200,
    alt: "The stone and earth houses of Aroumd stacked on a rocky spur above green trees, with High Atlas ridges behind.",
    source: "wikimedia",
    creator: "Macabe5387",
    licence: "CC BY-SA 4.0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:View_of_Aroumd.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Destination scenery only.",
    location: "Aroumd, near Imlil, Morocco",
  },
  {
    key: "e36-imlil-mule",
    src: "/images/e36-imlil-mule.jpg",
    width: 1600,
    height: 1200,
    alt: "A mule with a striped woven blanket on its back standing on a rocky mountain track above Imlil.",
    source: "wikimedia",
    creator: "Erokhin",
    licence: "CC BY-SA 4.0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:Imlil_and_its_valley_and_way_to_Jbel_Toubkal_18.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Attribution and share-alike required. No people in frame. Not a PM Travel supplier's animal.",
    location: "Imlil, High Atlas, Morocco",
  },
  {
    key: "e37-tamguist-valley",
    src: "/images/e37-tamguist-valley.jpg",
    width: 1600,
    height: 1064,
    alt: "Terraced green fields and trees threading along a valley floor below bare brown High Atlas mountains near Asni.",
    source: "wikimedia",
    creator: "DimiTalen",
    licence: "CC0",
    licenceProof:
      "https://commons.wikimedia.org/wiki/File:View_of_Tamguist_from_across_the_valley,_Morocco,_2008.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Public domain dedication. No people in frame. Destination scenery only.",
    location: "Tamguist, near Asni, High Atlas, Morocco",
  },
  {
    key: "e38-amssakrou-village",
    src: "/images/e38-amssakrou-village.jpg",
    width: 1600,
    height: 1064,
    alt: "The flat-roofed earthen houses of Amssakrou built up a steep valley side above a band of green fields.",
    source: "wikimedia",
    creator: "DimiTalen",
    licence: "CC0",
    licenceProof: "https://commons.wikimedia.org/wiki/File:Amssakrou,_Morocco,_2008.jpg",
    acquiredOn: "2026-09-14",
    commercialUse: true,
    restrictions: "Public domain dedication. No people in frame. Destination scenery only.",
    location: "Amssakrou, High Atlas, Morocco",
  },
];

export const imageByKey = (key: string): ImageRecord | undefined =>
  IMAGES.find((image) => image.key === key);

/** Only one image on the site may be priority-loaded: the LCP hero. */
export const priorityImageCount = IMAGES.filter((image) => image.priority).length;
